services:

  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbData:/var/lib/postgresql/data

  node:
    build: .
    command: yarn run dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres


volumes:
  db-data:
